pipeline:
    cwl-tests:
        image: ubuntu:14.04
        commands:
            - ./install-prerequisites.sh
            - /bin/bash -c 'source dx-toolkit/environment && ./run-tests.sh'
        secrets: [dxtoken]
